[theme]
primaryColor = "#E90080"  # Ralph's magenta color
backgroundColor = "#191919"  # Dark background 
secondaryBackgroundColor = "#333333"  # Darker gray for contrast
textColor = "#FFFFFF"  # White text for better readability on dark background
font = "monospace"  # More distinctive, technical look

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true
